# Generated by Django 3.0.5 on 2020-05-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_calendar', '0003_work_next_episode_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_ended',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='work',
            name='period',
            field=models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly')], max_length=10, null=True),
        ),
    ]
